// <auto-generated />
using System;
using ASP.NET_Core_Web_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_Core_Web_API.Migrations
{
    [DbContext(typeof(AspNetCoreWebApiDbContext))]
    [Migration("20231229113619_seeding data for regions and difficulties")]
    partial class seedingdataforregionsanddifficulties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_Core_Web_API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d000c5d0-96a2-48c6-b68a-8a49619851eb"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("509cc4c3-0ee9-4a90-8ffa-4fa335691cce"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("38e794c0-6acc-45af-a403-b46eb05a07a1"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("ASP.NET_Core_Web_API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d25b5e29-6ed4-49b9-8b49-f675c5763c10"),
                            Code = "R1",
                            Name = "Region 1",
                            RegionImageUrl = "https://example.com/region1-image.jpg"
                        },
                        new
                        {
                            Id = new Guid("a7f027c3-aea1-4af8-a756-a05409334e59"),
                            Code = "R2",
                            Name = "Region 2",
                            RegionImageUrl = "https://example.com/region2-image.jpg"
                        },
                        new
                        {
                            Id = new Guid("fd8b8ef3-d85c-4c16-9e09-d12e41d20763"),
                            Code = "R3",
                            Name = "Region 3",
                            RegionImageUrl = "https://example.com/region3-image.jpg"
                        },
                        new
                        {
                            Id = new Guid("1a66c0c7-2154-4175-9452-fbdd13961cc7"),
                            Code = "R4",
                            Name = "Region 4",
                            RegionImageUrl = "https://example.com/region4-image.jpg"
                        },
                        new
                        {
                            Id = new Guid("3834b42f-b6aa-47f5-8da3-e6fa262f1d49"),
                            Code = "R5",
                            Name = "Region 5",
                            RegionImageUrl = "https://example.com/region5-image.jpg"
                        });
                });

            modelBuilder.Entity("ASP.NET_Core_Web_API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("ASP.NET_Core_Web_API.Models.Domain.Walk", b =>
                {
                    b.HasOne("ASP.NET_Core_Web_API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_Core_Web_API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
